### ISSUE TITLE
System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by steven-fan-wu** [cxun/WeChatHistory#1]
Exception when load MM.sqlite

*************\* Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at WechatHistory.SpellCodeHelper.GetAllPYLetters(String transName)
   at WechatHistory.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by cxun** [comment]
Thanks for the exception! Can you provide me with the detailed string content stored in the variable transName in WechatHistory.SpellCodeHelper.GetAllPYLetters(String transName) function? That may help a lot to resolve the problem. Thank you very much~
